---
title: "R Notebook"
output: html_notebook
---

# Load Libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler", fig.width = 8, fig.height = 5)
```

```{r libraries, warning=FALSE}
# for data retrieval
library(gtrendsR)

# essential for data manipulation
library(tidyverse)
library(snakecase)

# render markdown in plots
library(ggtext)

# arrange plot distributions
library(patchwork)

# workflow management
library(here)
here::i_am("02-visualisations.Rmd")

# # fonts
# library(showtext)
# 
# font_add_google("Yanone Kaffeesatz", # name of the Google Font
#                 "Yanone Kaffeesatz") # name that will be used in R
# font_add_google("Fira Sans", "Fira Sans")
# 
# showtext_auto()

theme_set(theme_minimal(base_family = "Fira Sans"))
```

# Load Data

```{r}
keywords_volume <- read_csv('data/keywords.csv')

keywords_volume %>% head()
```

```{r}
keywords %>% 
  ggplot(aes(date, hits, col=keyword)) +
  geom_line() +
  labs(
    title = "Google Trends Daily Data",
    subtitle = "keywords: Mario Draghi, Christine Lagarde, European Central Bank, Euro",
    x = "Date",
    y = "Search Volumes"
  ) +
  theme(
    legend.position = "bottom"
  )
```

```{r}
keywords <- c("Mario Draghi", "Christine Lagarde", "European Central Bank", "Euro")
span <- "2012-01-01 2021-08-28"

for (keyword in keywords) {
  print(glue::glue("Retrieving {keyword} for {span}"))
  assign(
      glue::glue("{snakecase::to_snake_case(keyword)}_gtrends"),
      gtrends(keyword, time=span)$interest_over_time
    )
}
```

```{r}
gtrends_data <- mario_draghi_gtrends %>% 
  bind_rows(christine_lagarde_gtrends) %>% 
  bind_rows(euro_gtrends) %>% 
  bind_rows(european_central_bank_gtrends) %>%
  select(1:3)
```

